# Generated by Django 4.2.23 on 2025-08-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="client_name", new_name="customer_name",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="client_phone",
            new_name="customer_phone",
        ),
    ]
