# Generated by Django 4.2.23 on 2025-08-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_rename_client_name_appointment_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="appointment", unique_together=set(),),
        migrations.RemoveField(model_name="service", name="duration",),
        migrations.RemoveField(model_name="service", name="price",),
        migrations.AddField(
            model_name="service",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="color",
            field=models.CharField(default="#ff8da1", max_length=7),
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="citas.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
