# Generated by Django 4.2.23 on 2025-08-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_alter_appointment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("date", "time"), name="uniq_appointment_date_time"
            ),
        ),
    ]
