# Generated by Django 4.2.23 on 2025-08-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0004_appointment_uniq_appointment_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedslot",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blockedslot",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
