# Generated by Django 4.2.23 on 2025-09-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0005_blockedslot_end_time_blockedslot_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"verbose_name": "Cita", "verbose_name_plural": "Citas"},
        ),
        migrations.AlterModelOptions(
            name="blockedslot",
            options={
                "verbose_name": "Auto bloqueo",
                "verbose_name_plural": "Auto bloqueos",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
        migrations.RemoveConstraint(
            model_name="appointment", name="uniq_appointment_date_time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="citas.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="color",
            field=models.CharField(default="#0d6efd", max_length=7),
        ),
    ]
