# Generated by Django 4.2.25 on 2025-11-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_servicecategory_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_backgrounds/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fondo de inicio',
                'verbose_name_plural': 'Fondos de inicio',
            },
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Categoria de servicio', 'verbose_name_plural': 'Categorias de servicio'},
        ),
    ]
