# Generated by Django 4.2.25 on 2025-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_homebackground_alter_servicecategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('consult_price_with_owner', models.BooleanField(default=False, verbose_name="Mostrar 'Consultar precio con propietaria'")),
                ('is_vip_only', models.BooleanField(default=False, help_text='Si está marcado, la promo solo se mostrará en la sección VIP.', verbose_name='Solo clientes VIP')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Si lo dejas en blanco, se generará automáticamente.', max_length=4, unique=True, verbose_name='Código (4 dígitos)')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la clienta')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código VIP',
                'verbose_name_plural': 'Códigos VIP',
                'ordering': ['-created_at'],
            },
        ),
    ]
