# Generated by Django 4.2.25 on 2025-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_promotion_vipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPClientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Puede ser numérico de 4 dígitos o cualquier texto único.', max_length=10, unique=True, verbose_name='Código VIP')),
                ('note', models.CharField(blank=True, help_text='Referencia interna (ej. nombre de la clienta).', max_length=200, verbose_name='Nota / Nombre clienta')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código VIP',
                'verbose_name_plural': 'Códigos VIP',
            },
        ),
        migrations.DeleteModel(
            name='VipCode',
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='consult_price_with_owner',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_vip_only',
        ),
        migrations.AddField(
            model_name='promotion',
            name='show_price',
            field=models.BooleanField(default=True, help_text="Si se desmarca, se mostrará 'Consultar precio con propietaria'.", verbose_name='Mostrar precio al cliente'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='vip_only',
            field=models.BooleanField(default=False, help_text='Si se marca, este paquete solo se mostrará en la sección VIP.', verbose_name='Solo Clientes VIP'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
