# Generated by Django 4.2.25 on 2025-11-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_vipclientcode_delete_vipcode_alter_promotion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio (CRC)')),
                ('show_price', models.BooleanField(default=True, help_text="Si se desmarca, se mostrará 'Consultar precio con propietaria'.", verbose_name='Mostrar precio en la web')),
                ('vip_only', models.BooleanField(default=False, help_text='Si está marcado, este paquete solo se mostrará a clientas VIP.', verbose_name='Solo VIP')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código VIP')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la clienta')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código VIP',
                'verbose_name_plural': 'Códigos VIP',
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='VIPClientCode',
        ),
    ]
